### ISSUE TITLE
Resolves non included relationships

### ISSUE THREAD

**Issue by bondzula** [wopian/kitsu#374] opened 2020-03-06 12:27 UTC
Hi, I'm trying to implement kitsu-core `deserialise` method in Axios interceptor, which works just fine, however, I'm having an issue with relationships. Say for example resource has more than one relationship, the base object should include all of them inside relationship objects with corresponding links to them which are used for client discovery (in my case at least). Example without include:

```javascript
"relationships": {
  "author": {
    "links": {
      "self": "http://api.com/posts/1/relationships/authors",
      "related": "http://api.com/posts/1/authors"
    },
    "data": {}
  },
  "comments": {
    "links": {
      "self": "http://api.com/posts/1/relationships/comments",
      "related": "http://api.com/posts/1/comments"
    },
    "data": []
  },
}
```
And this works fine, as relationships are not being parsed, however, as soon as I include let's say `author` it will try to parse `comments` as well, and end up with `"comments": { id: undefined, type: undefined }` and there is no `"relationships"` object anymore, which is a problem for me, in case I wanna dynamically fetch the comments later on instead of including them on first request. What's more, it even tries to parse relationships of included resource, which are always going to resolve in an undefined type object like above

**Comment by wopian** [comment] 2020-03-12 12:22
Sorry this got drowned out in my GitHub notifications.

Looks like the code is not expecting the empty data object - it's not required by the spec. Although it shouldn't be returning undefined either. Likely just needs an extra condition to check the object/array is not empty.

As for the removal of relationships that were not included when an include was explicitly provided, that was by design when this was for my own personal use. I can change this as I never thought of that use case at the time and definitely feels counterintuitive now.

**Comment by wopian** [comment] 2020-05-02 01:36
Fixed the following in 8.3.1:

```
comments: { id: undefined, type: undefined }
```

**Comment by wopian** [comment] 2020-05-07 11:26
Links are fixed in 9.0.0

**Closed** 2020-05-07 11:33 UTC
Labels: bug, kitsu-core, test
