### ISSUE TITLE
Cannot POST client-generated IDs

### ISSUE THREAD

**Issue by matt-l-w** [wopian/kitsu#369] opened 2020-02-12 12:25 UTC
In the jsonapi spec, there is accommodation for [client-generated IDs](https://jsonapi.org/format/#crud-creating-client-ids). In this library, however, they are explicitly _not_ serialized in the request body.

See [this line in serilaize/index.js](https://github.com/wopian/kitsu/blob/6dd508093be95a4cec217dde319c8dedbe76832b/packages/kitsu-core/src/serialise/index.js#L112).
```js
...
} else if (key !== 'id' && key !== 'type') {
  data = serialiseAttr(node, key, data)
}
...
```

This is causing us quite an issue and we've had to put in a temporary vanilla `fetch` as a workaround.

Is there any specific reason for this being stripped out or can we accommodate it? Maybe as an optional parameter instead?

**Comment by wopian** [comment] 2020-02-12 17:44
Fixed with e4d84e00dcd1f4b603e92a400fa8fac3a19f4121. Waiting on macOS tests to finish running and will push a release out.

>See this line in serilaize/index.js.

That code is actually stopping `id` and `type` from being removed from the root level - otherwise the serialised data would look like:

```
data: {
	attributes: {
		id: '1',
		type: 'post'
	}
}
```

The problem was caused by this line
https://github.com/wopian/kitsu/blob/6dd508093be95a4cec217dde319c8dedbe76832b/packages/kitsu-core/src/serialise/index.js#L103

Now https://github.com/wopian/kitsu/blob/2e6f8db19d9ff86cea3e06aa9ca6d3175c95df11/packages/kitsu-core/src/serialise/index.js#L103

>Is there any specific reason for this being stripped out or can we accommodate it?

Not that I am aware of.

**Closed** 2020-02-12 17:44 UTC

**Comment by wopian** [comment] 2020-02-12 18:18
Released in `8.0.5`

**Comment by matt-l-w** [comment] 2020-02-13 10:17
This must take the trophy for fastest issue response/fix ever...
Thanks @wopian 👏

**Comment by wopian** [comment] 2020-02-13 17:33
And least amount of changes too!
